export const SET_USER = 'SET_USER';
export const SET_REGISTER_LOADING = 'SET_REGISTER_LOADING';
export const SET_REGISTER_DID_ERROR = 'SET_REGISTER_DID_ERROR';
export const SET_REGISTER_INPUT_ERRORS = 'SET_REGISTER_INPUT_ERRORS';
export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING';
export const SET_LOGIN_DID_ERROR = 'SET_LOGIN_DID_ERROR';
export const SET_LOGIN_INPUT_ERRORS = 'SET_LOGIN_INPUT_ERRORS';